doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      experience_id: App\Experience\Infrastructure\Persistence\Doctrine\Type\ExperienceIdType
      provider_id: App\Experience\Infrastructure\Persistence\Doctrine\Type\ProviderIdType
      experience_title: App\Experience\Infrastructure\Persistence\Doctrine\Type\TitleType
      experience_description: App\Experience\Infrastructure\Persistence\Doctrine\Type\DescriptionType
      session_id: App\Session\Infrastructure\Persistence\Doctrine\Type\SessionIdType
      session_starts_at: App\Session\Infrastructure\Persistence\Doctrine\Type\StartsAtType
      session_day: App\Session\Infrastructure\Persistence\Doctrine\Type\SessionDayType
      session_capacity: App\Session\Infrastructure\Persistence\Doctrine\Type\CapacityType
      booking_id: App\Booking\Infrastructure\Persistence\Doctrine\Type\BookingIdType
      user_id: App\Booking\Infrastructure\Persistence\Doctrine\Type\UserIdType
      booking_reference: App\Booking\Infrastructure\Persistence\Doctrine\Type\BookingReferenceType
      booking_seats: App\Booking\Infrastructure\Persistence\Doctrine\Type\SeatsType
  orm:
    enable_native_lazy_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    controller_resolver:
      auto_mapping: false
    mappings:
      Shared:
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Shared'
        prefix: 'App\Shared\Domain'
        is_bundle: false
      Experience:
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Experience'
        prefix: 'App\Experience\Domain'
        is_bundle: false
      Session:
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Session'
        prefix: 'App\Session\Domain'
        is_bundle: false
      Booking:
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Booking'
        prefix: 'App\Booking\Domain'
        is_bundle: false

when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
